#!/usr/bin/env python

import rospy
from segbot_concert_services.msg import AvailableRobotArray

def robot_publisher():
    pub = rospy.Publisher('/available_robots', AvailableRobotArray, latch=True)
    available_robots = rospy.get_param('~available_robots')
    pub.publish(available_robots.split(','))
    rospy.spin()

if __name__ == '__main__':
    try:
        rospy.init_node('robot_publisher', anonymous=True)
        robot_publisher()
    except rospy.ROSInterruptException:
        pass
